name: Run Selenium Bot

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual execution

jobs:
  selenium-job:
    runs-on: ubuntu-latest  # Runs on a Linux server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          echo "Installed Chrome version: $CHROME_VERSION"
          LATEST_CHROMEDRIVER=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
          echo "Downloading ChromeDriver version: $LATEST_CHROMEDRIVER"
          wget "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install selenium webdriver-manager

      - name: Run Selenium Script
        run: python test_bot.py
